## **Understanding Numpy**

* Numpy (Numerical Python) is the foundation library for scientific computing in Python. It provides a powerful N-dimesional array object and tools for working with these arrays.
* Think of Numpy as the engine that powers most data science libraries - pandas uses Numpy arrays internally, scikit-learn expects Numpy arrays for machine learning, and matplotlib uses Numpy for plotting.
* NumPy operations are implemented in C, making them 10-100x faster than pure Python
* Numpy arrays store data more compactly than Python lists
* Vectorization: Perform operations on entire arrays without writing loops
* Work with arrays of different shapes seamlessly
* Foundation for pandas, scikit-learn, matplotlib, and more

In [1]:
# import all necessary libaries
import numpy as np 
import matplotlib.pyplot as plt 
import time

# check Numpy version
print(f"NumPy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)

NumPy version: 2.3.2


We import Numpy with the standard alias `np`. The print options make arrays display more readably by limiting decimal places and avoding scientic notation for numbers like 0.001.

**Numpy Data Structure**
* Numpy arrays are fundamentally different from Python lists:
* Homogenous: All elements must be the same data type
* Fixed size: Size is determined at creation (though you can create new arrays)
* More efficient: Elements are stored in contiguous memory blocks
* Vectorized operations: Mathematical operations work on entire arrays

**Creating Numpy Arrays**

In [5]:
# Creating arrays from Python lists
# 1D array: A simple sequences of numbers
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array: Think of this as a matrix or table with rows and columns
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

# 3D array: Like a stack of 2D arrays - useful for images, time series, etc.
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print("1D array:", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


When you pass a nested list to np.array(), NumPy automatically determines the dimensions. The 1D array is like a single row, 2D is like a spreadsheet, and 3D is like multiple spreadsheets stacked together.

**Creating Special Arrays in Numpy**

In [4]:
# Creating arrays filled with zeros - useful for initializing arrays
# Shape (3, 4) means 3 rows and 4 columns
zeros = np.zeros((3, 4))

# Creating arrays filled with ones = often used as starting points
ones = np.ones((2, 3, 4))       # 3D array: 2 layers, 3 rows, 4 columns

# Empty array - faster than zeros/ones but contains random values
# Use when you'll immediatly fill the array with real data
empty = np.empty((2, 2))

print("Zeros array (3x4): \n", zeros)
print("Ones array shape: ", ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array (3x4): 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape:  (2, 3, 4)
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


`zeros()` and `ones()` are memory-efficient ways to create arrays of specific sizes. `empty()` is fastest but contains garbage values, so only use it when you'll immediately overwrite the contents.

In [ ]:
# Range arrays - like Python's range() but more powerful
range_arr = np.arange(0, 10, 2)     # start, stop, step: [0, 2, 4, 5, 8]
print("Range array:", range_arr)

# Linearly spaced arrays - divide a range into equal parts
# From 0 to 1 with exactly 5 points (including endpoints)
linspace_arr = np.linspace(0, 1, 5)
print("Linspace array:", linspace_arr)

# Logarithmically spaced arrays - useful for scientific data
# From 10^0 to 10^2 (1 to 100) with 5 points
logspace_arr = np.logspace(0, 2, 5)
print("Logspace array:", logspace_arr)

Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


* `arange()` works like Python's range() but returns a Numpy array and works with floats
* `linspace()` divides a range into equal segments - useful for plotting smooth curves. 
* `logspace()` creates points that are evenly spaced on a logarithmic scale

In [7]:
# Identify matrix - diagonal of ones, zero elsewhere
# Essential for linear algebra operations
identity = np.eye(4)            # 4x4 identity matrix

# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1, 2, 3, 4])

# Array filled with a specific value
full_arr = np.full((3, 3), 7)   # 3x3 array filled with 7

print("Identify matrix:\n", identity)
print("Diagonal matrix:\n", diagonal)
print("Full array (filled with 7):\n", full_arr)

Identify matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


Identity matrices are crucial in linear algebra - multiplying any matrix by identity matrix returns the original matrix. Diagonal matrices are useful for scaling operations.

**Numpy Data Types (dtypes)**
* Understanding data types is crucial for memory efficiency and numerical precision.

In [ ]:
# Explicit data types - control memory usage and precision
int_arr = np.array([1, 2, 3], dtype=np.int32)       # 32-bit integers
float_arr = np.array([1, 2, 3], dtype=np.float64)   # 64-bit floats (double precision)
bool_arr = np.array([True, False, True], dtype=np.bool_)        # Boolean values

# Type conversion - change dtype of existing array
converted = int_arr.astype(np.float32)      # convert to 32-bit float

print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)
print("Converted array dtype:", converted.dtype)

# Memory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

Integer array dtype: int32
Float array dtype: float16
Boolean array dtype: bool
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 2 bytes per element


* int8: 1byte, range - 128 to 127
* int32: 4bytes, range +- 2billion
* float32: 4 bytes, ~7 decimal digits precision
* float64: 8 bytes, ~15 decimal digits precision
* Choose smaller types to save memory, larger types for precision

**Array Properties & Attributes**
* Understanding array properties helps you work effectively with your data and debug issue

In [15]:
# Create a sample 3D array for demonstration
# Think of this as 3 layers, each with 4 rows and 5 columns
arr = np.random.randn(3, 4, 5)

# Shape: The dimensions of the array (layers, rows, colums)
print("Shape:", arr.shape)          # Output:  (3, 4, 5)

# Size: Total number of elements (3 x 4 x 5 = 60)
print("Size:", arr.size)

# Ndim: Number of dimensions (3D in this case)
print("Ndim:", arr.ndim)

# Dtype: Data type of elements
print("Dtype:", arr.dtype)          # Usually float64 for random numbers

# Itemsize: Memory size of each element in bytes
print("Itemsize:", arr.itemsize)        # 8 bytes for float64

# Total memory usage in bytes
print("Memory usage:", arr.nbytes, "bytes")     # size x itemsize
print("Memory usage:", arr.nbytes / 1024, "KB")     # Convert to KB

Shape: (3, 4, 5)
Size: 60
Ndim: 3
Dtype: float64
Itemsize: 8
Memory usage: 480 bytes
Memory usage: 0.46875 KB


These properties are essential for understanding your data's structure and memory requirements. Large datasets require careful attention to memory usage.

**Array Indexing & Slicing**

**Basic Indexing - Accessing Individual Elements**
* NumPy indexing is similar to Python lists but more powerful for multi-dimensional arrays

In [16]:
# 1D array indexing - similar to Python lists
arr1d = np.array([10, 20, 30, 40, 50])

print("First element:", arr1d[0])       # Index 0: 10
print("Large element:", arr1d[-1])      # Negative indexing: 50
print("Slice [1:4]", arr1d[1:4])        # Elements 1, 2, 3: [20, 30, 40]
print("Every 2nd element:", arr1d[::2]) # step of 2: [10, 30, 50]

First element: 10
Large element: 50
Slice [1:4] [20 30 40]
Every 2nd element: [10 30 50]


Negative indices count from the end (-1 is last element). Slicing uses [start:stop:step] where stop is exclusive.

In [ ]:
# 2D array indexing - row and column access
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access specific element: [row, column]
print("Element at row 1, column 2:", arr2d[1, 2])       # 7

# Access entire rows and columns
print("First row:", arr2d[0, :])                # all columns of row 0
print("Second column:", arr2d[:, 1])            # all rows of column 1

# Subarray slicing: [row_start:row_end, col_start:col_end]
print("Subarray (rows 1-2, cols 1-2:)\n", arr2d[1:3, 1:3])

The comma separates dimensions. : means "all elements along this dimension". Slicing creates views of the original data when possible, not copies.

**Advanced Indexing - Powerful Selection Methods**

In [ ]:
# Fancy indexing - use arrays of indices to select elements
arr = np.array([10, 20, 30, 40 50])
indices = np.array([0, 2, 4])       # select elements at positioins 0, 2, 4
print("Fancy indexing:", arr[indices])          # [10, 30, 50]

# This is much more flexible than simple slicing
random_indices = np.array([4, 1, 3, 1])     # can repeat and reorder
print("Random order:", arr[random_indices])         # [50, 20, 40, 20]

SyntaxError: invalid syntax (312130335.py, line 2)

: 

Fancy indexing lets you select elements in any order, repeat elements, and select non-contiguous elements. Very useful for data sampling and reordering.

In [ ]:
# 2D fancy indexing - select specific row/column combinations
arr2d = np.arange(12).reshape(3, 4)     # 3x4 array: [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
print("Original 2D array:\n", arr2d)

# select elements at (row, col) pairs: (0,1) and (2, 3)
rows = np.array([0, 2])
cols = np.array([1, 3])
print("Elements at (0,1) and (2,3):", arr2d[rows, cols])        # [1, 11]

# Select entire rows using fancy indexing
selected_rows = arr2d[[0, 2], :]    # Rows 0 and 2, all columns
print("Selected rows:\n", selected_rows)

When you provide arrays for both dimensions, NumPy pairs them element-wise. This is different from slicing, which creates a rectangular subarray.

**Array Reshaping & Manipulation**
* Reshaping changes how the same data is organized in memory without changing the actual values.

In [ ]:
# Start with a 1D array
arr = np.arange(12)     # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print("Original 1D array:", arr)

# Reshape to 2D: 3 rows x 4 columns
reshaped_2d = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_2d)

# Reshape to 3D: 2 layers x 2 rows x 3 columns
reshaped_3d = arr.reshape(2, 2, 3)
print("Reshaped to 2x2x3:\n", reshaped_3d)

# Use -1 to let NumPy calculate one dimension automatically
auto_reshape = arr.reshape(4, -1)       # 4 rows, NumPy calculates columns
print("Auto-reshaped to 4x?:\n", auto_reshape)

The total number of elements must remain the same (12 in this case). Using -1 tells NumPy to calculate that dimension automatically. Reshaping creates a view when possible, not a copy

In [ ]:
# Flattening - convert multi-dimensional array to 1D
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# flatten() always returns a copy
flattened = arr2d.flatten()

# ravel() returns a view if possible (faster, memory efficient)
ravel = arr2d.ravel()
print("Ravel (view if possible:)", ravel)

# Demonstrates the difference
arr2d[0, 0] = 999
print("After modifying original:")
print("Flattend (unchanged:)", flattened)       # copy is independent
print("Ravel (changed):", ravel)            # view reflects changes

Use `ravel()` when you don't need to modify the flattened array independently. Use `flatten()` when you need a separate copy that won't be affected by changes to the original.

**Transposing and Swapping Axes**
*Transposing is essential for matrix operations and changing data orientation

In [ ]:
# 2D transposition - flip rows and columns
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("Original shape:", arr2d.shape)       # (2, 3)
print("Original:\n", arr2d)

print("Transposed shape:", arr2d.T.shape)       # (3, 2)
print("Transposed:\n", arr2d.T)

# Alternative transpose methods
print("Transpose method:\n", arr2d.transpose())

Transposing swaps rows and columns. This is crucial for matrix multiplication and when you need to change data orientation (e.g., from samplesxfeatures to featuresxsamples)

In [ ]:
# Higher-dimensional transposition
arr3d = np.arange(24).reshape(2, 3, 4)  # 2 layers, 3 rows, 4 columns

# specify new axis order: (axis0, axis1, axis2) -> (axis2, axis0, axis1)
transposed_3d = arr3d.transpose(2, 0, 1)
print("Transposed 3D shape:", transposed_3d.shape)      # (4, 2, 3)

# moveaxis is another way to rearrange axes
moved = np.moveaxis(arr3d, 0, -1)     # Move first axis to last position
print("Moveaxis result shape:", moved.shape)

For 3D+ arrays, you specify the new order of axes. This is useful for reshaping data for different algorithms or visualization requirements.

**Concatenating and Splitting Arrays**
* Combining and dividing arrays is fundamental for data manipulation

In [ ]:
# Concatenation - joining arrays along existing axes
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along different axes
concat_rows = np.concatenate([arr1, arr2], axis=0)  # stack vertically
concat_cols = np.concatenate([arr1, arr2], axis=1)  # stack horizontally

print("Original arrays:")
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated vertically (axis=0):\n", concat_rows)
print("Concatenated horizontally (axis=1):\n", concat_cols)

`axis=0` means along rows (vertical stacking), `axis=1` means along columns (horizontal stacking). Arrays must have compatible shapes along the non-concatenated dimensions

In [ ]:
# Convenient stacking functions
vstack_result = np.vstack([arr1, arr2]) # same as concatenate with axis=0
hstack_result = np.hstack([arr1, arr2]) # same as concatenate with axis=1
dstack_result = np.dstack([arr1, arr2]) # stack along depth (3rd dimension)

print("vstack (vertical):\n", vstack_result)
print("hstack (horizontal): \n", hstack_result)
print("dstack shape:", dstack_result.shape)     # creates 3D array

# Splitting arrays - opposite of concatenation
arr = np.arange(12).reshape(3, 4)
split_arrys = np.split(arr, 3, axis=0)      # split into 3 parts along rows
print("Original array for splitting:\n", arr)
print("Split into 3 parts along rows:")
for i, split_part in enumerate(split_arrays):
    print(f"Part {i}:\n", split_part)

Stacking functions are shortcuts for concatenation. Splitting divides an array into equal parts - useful for creating training/validation sets or processing in data chunks.

**Mathematical Operations**

**Element-wise Operations - The Power of Vectorization**
* NumPy's biggest advantage is performing operations on entire arrays without writing loo

In [ ]:
# Basic arithmetic operations work element-by-element
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print("Array 1:", arr1)
print("Array 2:", arr2)

# All operations happen element-wise automatically
print("Addition:", arr1 + arr2)         # [11, 22, 33, 44]
print("Subtraction:", arr2 - arr1)      # [9, 18, 27, 36]
print("Multiplication:", arr1 * arr2)   # [10, 40, 90, 160]
print("Divison:", arr2 / arr1)          # [10, 10, 10, 10]
print("Power:", arr1 ** 2)              # [1, 4, 9, 16]
print("Modulo:", arr2 % 3)              # [1, 2, 0, 1]

This vectorization is much faster than Python loops because the operations are implemented in optimized C coce. Each operation applies to corresponding elements.

In [ ]:
# Operations with scalars - broadcasting in action
print("Scalar operations:")
print("Add 10 to all elements:", arr1 + 10)     # [11, 12, 13, 14]
print("Multiply all by 3:", arr1 * 3)           # [3, 6, 9, 12]
print("Divide all by 2:", arr1 / 2)         # [0.5, 1, 1.5, 2]

# Compound operations
result = (arr1 + 5) * 2 - 1         
print("Compound operation (arr1 + 5) * 2 - 1:", result)

When you operate on arrays with scalars, the scalar is automatically "broadcast" to match the array shape. This much more readable and efficient that manual loops

**Mathematical Functions - Beyond Basic Arithmetic**
* NumPy provides vectorized versions of most mathematical function

In [ ]:
# Common mathematical functions
arr = np.array([1, 4, 9, 16, 25])
print("Original array:", arr)

# Square roots and powers
print("Square root:", np.sqrt(arr))         # [1, 2, 3, 4, 5]
print("Square:", np.square(arr))            # [1, 16, 81, 256, 625]
print("Cube root:", np.cbrt(arr))

# Exponential and logarithmic functions
small_arr = np.array([1, 2, 3])
print("Exponential:", np.exp(small_arr))    # [e^1, e^2, e^3]
print("Natural log:", np.log(arr))          # ln(arr)
print("Log base 10:", np.log10(arr))
print("Log base 2:", np.log2(arr))

These functions are much faster than applying Python's math functions in a loop. They also handle edge cases (like log of zero) more gracefully.

In [ ]:
# Trigonometric functions - essential for signal processing and geometry
angles = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Angles (radians):", angles)         
print("Sine:", np.sin(angles))              # [0, v2/2, 1, 0]
print("Cosine:", np.cos(angles))            # [1, v2/2, 0, -1]
print("Tangent:", np.tan(angles))           # [0, 1, infinite, 0]

# Convert degrees to radians
degrees = np.array([0, 45, 90, 100])
radians = np.deg2rad(degrees)
print("Degrees to radians:", radians)

Trigonometric functions expect angles in radians. Use `deg2rad()` and `rad2deg()` for conversions. These functions are essential for signal processing, computer graphics, and physics simulations.

In [ ]:
# Rounding and comparison functions
decimals = np.array([1.234, ,5.678, 9.999, -2.345])
print("Original decimals:", decimals)

print("Round to 2 places:", np.round(decimals, 2))
print("Floor (round down):", np.floor(decimals))        # [1, 5, 9, -3]
print("Ceiling (round up):", np.ceil(decimals))         # [2, 6, 10, -2]
print("Truncate (toward zero):", np.trunc(decimals))    # [1, 5, 9, -2]

# Absolute values and sign
print("Absolute values:", np.abs(decimals))
print("Sign (-1, 0, or 1):", np.sign(decimals))

Different rounding functions serve different purposes. `floor()` always rounds down, `ceil()` always rounds up, `trunc()` removes the decimal part, and `round()` rounds to nearest value.

**Aggregate Functions - Summarizing Your Data**
- Aggregate functions reduce arrays to summary statistics

In [ ]:
# Create a 2D array for demonstration
arr = np.array([[1, 2, 3],
                [4, 5, 6]
                [7, 8, 9]])
print("Sample array:\n", arr)

# Aggregation across entire array
print("Sum of all elements:", np.sum(arr))      # 45
print("Mean of all elements:", np.mean(arr))    # 5.0
print("Standard deviationi:", np.std(arr))      # 2.58
print("Minimum value:", np.min(arr))            # 1
print("Maximum value:", np.max(arr))            # 9

When you don't specify an axis, these functions operate on the flattened array, giving you a single summary value for the entire dataset.

In [ ]:
# Axis-specific aggregatioin - this is where NumPy shines!
print("Sum along axis 0 (columns):", np.sum(arr, axis=0))       # [12, 15, 18]
print("Sum along axis 1 (rows):", np.sum(arr, axis=1))          # [6, 16, 24]

print("Mean along axis 0:", np.mean(arr, axis=0))               # [4, 5, 6]
print("Mean along axis 1:", np.mean(arr, axis=1))               # [2, 5, 8]

# Finding position of extreme values
print("Position of max (flattened):", np.argmax(arr))       # 8 (element 9 at position 8)
print("Position of max along axis 0:", np.argmax(arr, axis=0))  # [2, 2, 2]
print("Position of max along axis 1:", np.argmax(arr, axis=1))  # [2, 2, 2]

* `axis=0`: Operations go "down"the rows (result has same number of columns)
* `axis=1`: Operations go "across" the columns (result has same number of rows)
* `argmax/argmin` return indices, not values

**Broadcasting**
* Broadcasting is NumPy's way of performing operations on arrays with different shapes without explicitly reshaping them. This is one of NumPy's most powerful features

In [ ]:
# Broadcasting examples - arrays don't need the same shape!
scalar = 5
arr1d = np.array([1, 2, 3, 4])
arr2d = np.array([[10], [20], [30]])        # column vector

print("Scalar:", scalar)
print("1D array:", arr1d)
print("2D array (column vector):\n", arr2d)

# Scalar broadcasts to any shape
result1 = scalar + arr1d 
print("Scalar + 1D array:", result1)       # [6, 7, 8, 9]

# 2D + 1D broadcasting
result2 = arr2d + arr1d 
print("2D + 1D broadcasting:\n", result2)

* Broadcasting follows these rules:
* Start from the trailing (rightmost) dimensions
* Dimensions are compatible if they're equal or one is 1
* Missing dimensions are assumed to be 1

In [ ]:
# Visualizing broadcasting step by step
a = np.arange(4).reshape(4, 1)          # Shape: (4, 1)
b = np.arange(5).reshape(1, 5)          # Shape: (1, 5)

print("Array a (4x1):\n", a)
print("Array b (1x5):\n", b)

# Broadcasting creates a 4x5 result
result = a + b                      # Result shape: (4, 5)
print("Broadcasting result (4x5):\n", result)
print("Result shape:", result.shape)

Array `a` gets broadcast horizontally, array `b` gets broadcast vertically. This creates all pairwise combinations without storing redundant data.

In [ ]:
# Manual broadcasting with newaxis
arr = np.array([1, 2, 3])
print("Original array shape:", arr.shape)           # (3,)

# Convert to column vector
column_vector = arr[:, np.newaxis]              # same as arr.reshape(-1, 1)
print("Column vector shape:", column_vector.shape)      # (3, 1)
print("Column vector:\n", column_vector)

# Convert to row vector (usually not needed - 1D arrays broadcast as rows)
row_vector = arr[np.newaxis, :]         # same as arr.reshape(1, -1)
print("Row vector shape:", row_vector.shape)        # (1, 3)

`np.newaxis` is an alias for None and adds a new axis of length 1. This gives you explicit control over broadcasting behavior

**Common Broadcasting Patterns**

In [ ]:
# Pattern 1: Centering data (subtract mean from each column)
data = np.random.randn(5, 3)        # 5 samples, 3 features
print("Original data shape:", data.shape)
print("Original data:\n", data)

# Calculate mean for each column
column_means = np.mean(data, axis=0)        # Shape: (3,)
print("Column means:", column_means)

# Subtract mean from each column (broacasting!)
centered_data = data - column_means         # (5, 3) - (3,) broadcast
print("Centered data:\n", centered_data)
print("New column means (should be ~0):", np.mean(centered_data, axis=0))

This is a common  preprocessing step in machine learning. The column means broadcast across all rows automatically.

In [ ]:
# Patern 2: Normalizing by row sums (useful for probabilities)
data = np.random.rand(4, 3)         # Ramdom data
print("Random data:\n", data)

# Calculate row sums
row_sums = np.sum(data, axis=1, keepdims=True)      # Shape: (4, 1)
print("Row sums shape:", row_sums.shape)
print("Row sums:\n", row_sums)

# Normalize each row to sum to 1
normalized = data / row_sums                    # (4, 3) / (4,1) broadcasts
print("Normalized data (rows sum to 1):\n", normalized)
print("Row sums after normalization:", np.sum(normalized, axis=1))

`keepdims=True` preserves the dimension at size 1, making broadcasting explicit and avoiding shape errors.